### ISSUE TITLE
Start frame > 1 pushes last image beyond the end

### ISSUE THREAD

**Issue by tylerecouture** [hapit/blender_addon_dynamic_slideshow#19]
Hi!  Thank you so much for this add-on!

I noticed that when I create a slideshow where the start frame >1, say 25, then the last image in the slideshow occurs after the end of the last frame (25 frames beyond in this case) of the animation and needs to be deleted and re-added to get it to work properly.

**Comment by hapit** [comment]
Thx for the feedback. I added the issue for the v0.5 milestone.

**Comment by hapit** [comment]
fixed with commit e469d65360f19fe42253c8351a4d692ec67e3ba3
